// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZUSlz5o80Q1Ki4UyK4-jF_tqApTZ5lvc',
    appId: '1:812408649150:web:55cd8aed3df2afe9dbf5ef',
    messagingSenderId: '812408649150',
    projectId: 'event-reminder-1d413',
    authDomain: 'event-reminder-1d413.firebaseapp.com',
    storageBucket: 'event-reminder-1d413.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAThB6tKcQs3AnQQamvv1s31x_iECt-Uug',
    appId: '1:812408649150:android:5c1630c9d67c6094dbf5ef',
    messagingSenderId: '812408649150',
    projectId: 'event-reminder-1d413',
    storageBucket: 'event-reminder-1d413.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAygkTKyVty1DQqRvFD9xiSgTxosWDbDsU',
    appId: '1:812408649150:ios:af5cb76d85f51e55dbf5ef',
    messagingSenderId: '812408649150',
    projectId: 'event-reminder-1d413',
    storageBucket: 'event-reminder-1d413.firebasestorage.app',
    iosBundleId: 'com.example.eventReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAygkTKyVty1DQqRvFD9xiSgTxosWDbDsU',
    appId: '1:812408649150:ios:af5cb76d85f51e55dbf5ef',
    messagingSenderId: '812408649150',
    projectId: 'event-reminder-1d413',
    storageBucket: 'event-reminder-1d413.firebasestorage.app',
    iosBundleId: 'com.example.eventReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZUSlz5o80Q1Ki4UyK4-jF_tqApTZ5lvc',
    appId: '1:812408649150:web:6595444169e3c5c9dbf5ef',
    messagingSenderId: '812408649150',
    projectId: 'event-reminder-1d413',
    authDomain: 'event-reminder-1d413.firebaseapp.com',
    storageBucket: 'event-reminder-1d413.firebasestorage.app',
  );
}
